arch: vits
weights: LVD1689M
pretrained: true
mask_ratio: 0.95
num_source_frames: 4
bptt_truncate: true
decoder_dim: 512
num_target_frames: 4
decoder_heads: 8
decoder_blocks: 4
gru_heads: 6
gru_blocks: 4
